window.walkthroughSteps = [
  {
    id: 'hero',
    label: 'Hero',
    selector: '#hero',
    audio: 'public/audio/01-hero.mp3',
    caption: 'Hi, I am Mujtaba Mohimtulay, an AI and Machine Learning Engineer based in Dubai. This portfolio introduces my background, experience, skills, and applied AI projects.',
    highlights: [
      { start: 0, end: 5, selector: '#hero', caption: 'A quick introduction to the portfolio.' },
      { start: 5, end: 6, selector: '#hero-title', caption: 'The headline frames the portfolio around practical AI engineering.' },
      { start: 6, end: 15, selector: '#hero-tags', caption: 'Core focus areas include LLMs, RAG, computer vision, NLP, PyTorch, and multi-agent AI.' },
      { start: 15, end: 32, selector: '#hero-stats', caption: 'The stats summarize experience, coding background, hackathon placement, and MSc focus.' },
    ],
  },
  {
    id: 'about',
    label: 'About',
    selector: '#about',
    audio: 'public/audio/02-about.mp3',
    caption: 'This section gives a deeper overview of my AI engineering background, education, and interest in reliable real-world systems.',
    highlights: [
      { start: 0, end: 5, selector: '#about', caption: 'The about section expands on my background.' },
      { start: 5, end: 15, selector: '#about-summary', caption: 'My work spans conversational AI, computer vision pipelines, RAG systems, and multi-agent workflows.' },
      { start: 15, end: 27, selector: '#education', caption: 'My academic foundation includes AI and machine learning degrees from Birmingham and Heriot-Watt.' },
      { start: 27, end: 40, selector: '#about-engineering-focus', caption: 'The focus is turning modern AI techniques into useful, production-minded applications.' },
    ],
  },
  {
    id: 'experience',
    label: 'Experience',
    selector: '#experience',
    audio: 'public/audio/03-experience.mp3',
    caption: 'My recent experience covers enterprise RAG, multi-agent orchestration, conversational AI, OCR, and production application development.',
    highlights: [
      { start: 0, end: 3, selector: '#experience', caption: 'The experience timeline shows applied AI and software engineering roles.' },
      { start: 3, end: 9, selector: '#experience-msbc', caption: 'At MSBC Group, I worked across practical AI engineering use cases.' },
      { start: 9, end: 14, selector: '#experience-msbc-rag', caption: 'I built RAG systems with OpenAI, NVIDIA NIM, and custom retrieval pipelines.' },
      { start: 14, end: 20, selector: '#experience-msbc-agents', caption: 'I designed multi-agent workflows for orchestration and information retrieval.' },
      { start: 20, end: 27, selector: '#experience-msbc-conversational-ai', caption: 'Conversational AI work combined STT, TTS, and function calling.' },
      { start: 27, end: 34, selector: '#experience-msbc-ocr', caption: 'OCR and vision-language pipelines helped extract information from documents.' },
      { start: 34, end: 46, selector: '#experience-alyousuf', caption: 'At Al Yousuf Group, I built production applications with Django, Flutter, and REST APIs.' },
      { start: 46, end: 75, selector: '#experience-summary', caption: 'That software background strengthens the product and engineering side of my AI systems.' },
    ],
  },
  {
    id: 'skills',
    label: 'Skills',
    selector: '#skills',
    audio: 'public/audio/04-skills.mp3',
    caption: 'This section summarizes the programming, AI, application, database, and specialization stack I use to build applied AI systems.',
    highlights: [
      { start: 0, end: 5, selector: '#skills', caption: 'The skills section groups my technical stack.' },
      { start: 5, end: 10, selector: '#skills-languages', caption: 'Programming languages include Python, JavaScript, C Sharp, HTML, CSS, SQL, and Dart.' },
      { start: 10, end: 21, selector: '#skills-ai-ml', caption: 'The AI stack includes PyTorch, TensorFlow, OpenAI APIs, NVIDIA NIM, FAISS, RAG, LLMs, computer vision, NLP, and Gemini.' },
      { start: 21, end: 32, selector: '#skills-frameworks', caption: 'Framework and tooling experience includes Django, FastAPI, Flutter, Streamlit, NumPy, Pandas, Git, and REST APIs.' },
      { start: 32, end: 36, selector: '#skills-databases', caption: 'Database experience includes MySQL, PostgreSQL, and SQLite.' },
      { start: 36, end: 47, selector: '#skills-specializations', caption: 'Specializations include agents, speech AI, OCR, vision-language models, YOLO, anomaly detection, and agentic RAG.' },
      { start: 47, end: 70, selector: '#skills-summary', caption: 'Together, the stack covers model experimentation, backend integration, and user-facing applications.' },
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    selector: '#projects',
    audio: 'public/audio/05-projects.mp3',
    caption: 'The projects section shows applied AI systems across computer vision, LLM reasoning, RAG, safety evaluation, and agentic workflows.',
    highlights: [
      { start: 0, end: 9, selector: '#projects', caption: 'Projects show how the AI stack is applied to real problems.' },
      { start: 10, end: 33, selector: '#project-evalops-ai', caption: 'AI evaluation and governance platform for testing LLM, RAG, and agentic systems for safety, reliability, regressions, and tool-call behavior.' },
      { start: 34, end: 63, selector: '#project-nexusops-ai', caption: 'MCP-powered operations copilot that connects business data, policies, CRM, tasks, and human approval workflows for Dubai real estate teams.' },
      { start: 64, end: 83, selector: '#project-vigilai', caption: 'VigilAI combines emergency detection, anomaly detection, LLM reasoning, and agentic incident reporting.' },
      { start: 84, end: 92, selector: '#projects-summary', caption: 'Together, the projects demonstrate applied AI across vision, LLMs, RAG, and safety.' },
    ],
  },
  {
    id: 'contact',
    label: 'Contact',
    selector: '#contact',
    audio: 'public/audio/06-contact.mp3',
    caption: 'The contact section makes it easy to reach out for AI engineering roles, freelance projects, internships, and collaborations.',
    highlights: [
      { start: 0, end: 5, selector: '#contact', caption: 'The final section is about getting in touch.' },
      { start: 5, end: 15, selector: '#contact-opportunities', caption: 'I am open to roles and projects in AI, ML, LLMs, RAG, and intelligent applications.' },
      { start: 15, end: 24, selector: '#contact-location', caption: 'I am based in Dubai, hold a UAE Golden Visa, and am open to local or global teams.' },
      { start: 24, end: 36, selector: '#contact-links', caption: 'Visitors can reach me through email, LinkedIn, GitHub, or phone.' },
    ],
  },
];

window.quickTourSteps = [
  {
    id: 'quick-tour',
    label: 'Quick Tour',
    selector: '#hero',
    audio: 'public/audio/quick-tour.mp3',
    caption: 'A fast overview of my AI engineering background, experience, projects, and contact details.',
    highlights: [
      { start: 0, end: 12, selector: '#hero', caption: 'I am an AI and Machine Learning Engineer based in Dubai.' },
      { start: 12, end: 18, selector: '#about', caption: 'My background combines AI engineering, software development, and applied machine learning.' },
      { start: 18, end: 28, selector: '#education', caption: 'My academic foundation includes AI and machine learning degrees from Birmingham and Heriot-Watt.' },
      { start: 28, end: 30, selector: '#experience', caption: 'Recent work includes RAG systems, multi-agent frameworks, conversational AI, OCR, and vision-language models.' },
      { start: 30, end: 38, selector: '#experience-msbc', caption: 'At MSBC Group, I worked across practical AI engineering use cases.' },
      { start: 38, end: 41, selector: '#projects', caption: 'Featured projects include VigilAI, EvalOps AI, and NexusOps AI.' },
      { start: 41, end: 45, selector: '#project-evalops-ai', caption: 'AI evaluation and governance platform for testing LLM, RAG, and agentic systems for safety, reliability, regressions, and tool-call behavior.' },
      { start: 45, end: 50, selector: '#project-nexusops-ai', caption: 'MCP-powered operations copilot that connects business data, policies, CRM, tasks, and human approval workflows for Dubai real estate teams.' },
      { start: 50, end: 54, selector: '#project-vigilai', caption: 'VigilAI combines emergency detection, anomaly detection, LLM reasoning, and agentic incident reporting.' },
      { start: 54, end: 70, selector: '#contact', caption: 'I am open to AI engineering roles, freelance projects, and collaborations.' },
    ],
  },
];
